= restic-backup-wrapper tool
:source-language: shell
:source-highlighter: pygments
:pygments-css: class
:icons: font
:opt: (optional)
:cli: restic-backup-wrapper-cli
:rt: restic

*{cli}* is a command-line tool that generates https://restic.readthedocs.io/en/latest/040_backup.html[`{rt}`] commands from a TOML config file.

The output is suitable for piping to a (Posix) shell.
If you have the `RESTIC_REPOSITORY` and `RESTIC_PASSWORD` environment variables set up already, you can run it simply as:

[subs=attributes]
----
{cli} -l '' -i my-backup.toml | bash -xs
----

CAUTION: _Please note although this script is provided in the hope it will be link:LICENSE[useful], use caution when running it.
Always review the generated `{rt}` commands, as improper use could potentially damage your backup data._

== Example

Given a link:min.toml[TOML file] `min.toml`:

[,toml]
----
include::min.toml[]
----

then

[subs=attributes]
----
{cli} -l '' -i min.toml
----

generates `{rt}` commands:

----
include::{min-sh}[]
----

== Syntax

[,text]
----
include::{doc-help}[]
----

== Prerequisites

* https://hatch.pypa.io/[`hatch`] -- install via `pipx hatch` or `pip install --user hatch`

== How to use

----
# run the CLI
hatch run cli
make cli

# run the CLI help
hatch run help
make help

# or append any CLI-defined args, like --help
hatch run cli --help
make cli EXTRA='...'

# run mypy
hatch run types:check
make mypy

# run tests
make
hatch run test

# go to the venv shell
hatch shell

# write documentation
make doc

# increase version
hatch version <new-version>
----

== Local install and run

[subs="attributes"]
----
rm -rf dist/
hatch build
pipx install dist/*.whl
{cli} --version
{cli} --help

# or you can use
make local
----

== Input file format

`-i`/`--input-file` is a TOML file of the following format.

=== Global parameters

`restic-repo` {opt}::
If specified, `{rt} -r <restic-repo>` will be generated.
If not specified `-r XXX` will omitted.
I do not use this flag as my `{rt}` is actually a custom alias/wrapper that sets my {rt} repo password as an environment variable.

`relative-to` {opt}::
If specified, all `dir` paths (see below) that are relative to this path will be backed up as relative.
+
====
If `relative-to="X"` and a `dir="X/Y"` then the generated command will be `(cd X && {rt} backup Y ...)`.
====

`group-by` {opt}::
Translates to `--group-by` {rt} flag.
It will be omitted from the generated command if not specified.

`exclude` {opt}::
Add these exclude patterns to every generated command.
The folder-specific excludes will be merged with this exclude, if any.

=== Backed up folders

Each key of the form `[my-dir]` represents a folder to be backed up and for which a `{rt} backup` command will be generated.

TIP: The key can be an arbitrary string and does not need to match folder/file being backup up.

For each such entry, `{cli}` recognizes these parameters:

`dir` (mandatory)::
Path to back up; if `relative-to` is set in the global parameters to a path `X`, `dir` will end up backed up as relative to `X` if it is a descendant path of `X`; otherwise it is kept as is.

`tags` {opt}::
A list of tags; tags `['x','a tag with space']` will end up as `{rt} backup ... --tag 'a tag with space,x' ...` (spaces in the tags are allowed).

`exclude` {opt}::
Exclude patterns relevant to this folder.
These patterns, if any, will be merged with the global `exclude`.

`keep-last` (optional; added in version `0.2.0`)::
Generate _another_ line to keep only the specified number of snapshots, something like `{rt} ... forget --prune --keep-last <N> --path <full-folder-path>`.

== {rt} and relative paths

According to https://forum.restic.net/t/backing-up-restoring-relative-paths/744/2[the {rt} author], {rt} keeps relative and absolute paths.
It is not obvious from `{rt} snaphots` where only absolute paths are shown.
Running `{rt} ls <snapshot-id>` for a snapshot backed up from a relative path will show `/` as the "parent" path (and not the full path).

_So one should imagine how `tar` does it._

== Writing documentation

When writing documentation, edit `source_readme.adoc`, run `make doc-devel` and preview the generated `readme.html`.

Once ready to commit, run `make doc` to generate link:README.md[README.md] file from link:source_readme.adoc[source_readme.adoc] (and included files).

